# Exercise - Create Infra
AWSTemplateFormatVersion: 2010-09-09
Description: Proj 3 - Create Infra 
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: project3
      ImageId: 'ami-0c4f7023847b90238' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
      InstanceType: t3.micro

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0