version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

  add_public_ip_to_hosts_file: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Add public ip to ansible inventory
          command: |
            echo "[all]" > /tmp/inventory.txt 
            echo "54.92.254.115" >> /tmp/inventory.txt 
            cat /tmp/inventory.txt           
            

  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              fingerprints: ["8c:91:a3:3d:53:6d:e5:9b:4c:82:61:cb:d9:39:8a:2c"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i .circleci/ansible/inventory.txt main-remote.yml

workflows:
  my-workflow:
    jobs:
      - create_infrastructure
      - add_public_ip_to_hosts_file
      - configure_infrastructure:
          requires :
            - add_public_ip_to_hosts_file
            - create_infrastructure
